export const CALENDAR_REQUEST = "CALENDAR_REQUEST";
export const CALENDAR_SUCCESS = "CALENDAR_SUCCESS";
export const CALENDAR_FAILURE = "CALENDAR_FAILURE";

export const WINNERS_ROUND_ONE_REQUEST = "WINNERS_ROUND_ONE_REQUEST";
export const WINNERS_ROUND_ONE_SUCCESS = "WINNERS_ROUND_ONE_SUCCESS";
export const WINNERS_ROUND_ONE_FAILURE = "WINNERS_ROUND_ONE_FAILURE";

export const WINNERS_ROUND_TWO_REQUEST = "WINNERS_ROUND_TWO_REQUEST";
export const WINNERS_ROUND_TWO_SUCCESS = "WINNERS_ROUND_TWO_SUCCESS";
export const WINNERS_ROUND_TWO_FAILURE = "WINNERS_ROUND_TWO_FAILURE";

export const WINNERS_ROUND_THREE_REQUEST = "WINNERS_ROUND_THREE_REQUEST";
export const WINNERS_ROUND_THREE_SUCCESS = "WINNERS_ROUND_THREE_SUCCESS";
export const WINNERS_ROUND_THREE_FAILURE = "WINNERS_ROUND_THREE_FAILURE";
