export const DRIVERS_REQUEST = 'DRIVERS_REQUEST';
export const DRIVERS_SUCCESS = 'DRIVERS_SUCCESS';
export const DRIVERS_FAILURE = 'DRIVERS_FAILURE';

export const DRIVERS_STANDINGS_REQUEST = 'DRIVERS_STANDINGS_REQUEST';
export const DRIVERS_STANDINGS_SUCCESS = 'DRIVERS_STANDINGS_SUCCESS';
export const DRIVERS_STANDINGS_FAILURE = 'DRIVERS_STANDINGS_FAILURE';
