export const LATEST_RACE_RESULT_REQUEST = 'LATEST_RACE_RESULT_REQUEST';
export const LATEST_RACE_RESULT_SUCCESS = 'LATEST_RACE_RESULT_SUCCESS';
export const LATEST_RACE_RESULT_FAILURE = 'LATEST_RACE_RESULT_FAILURE';

export const RACE_RESULT_REQUEST = 'RACE_RESULT_REQUEST';
export const RACE_RESULT_SUCCESS = 'RACE_RESULT_SUCCESS';
export const RACE_RESULT_FAILURE = 'RACE_RESULT_FAILURE';
