export const MOTOGP_ROUND_UP_DATA_REQUEST = '    MOTOGP_ROUND_UP_DATA_REQUEST';
export const MOTOGP_ROUND_UP_DATA_SUCCESS = '    MOTOGP_ROUND_UP_DATA_SUCCESS';
export const MOTOGP_ROUND_UP_DATA_FAILURE = '    MOTOGP_ROUND_UP_DATA_FAILURE';

export const RUGBY_ROUND_UP_DATA_REQUEST = '    RUGBY_ROUND_UP_DATA_REQUEST';
export const RUGBY_ROUND_UP_DATA_SUCCESS = '    RUGBY_ROUND_UP_DATA_SUCCESS';
export const RUGBY_ROUND_UP_DATA_FAILURE = '    RUGBY_ROUND_UP_DATA_FAILURE';

export const FOOTBALL_ROUND_UP_DATA_REQUEST =
  '    FOOTBALL_ROUND_UP_DATA_REQUEST';
export const FOOTBALL_ROUND_UP_DATA_SUCCESS =
  '    FOOTBALL_ROUND_UP_DATA_SUCCESS';
export const FOOTBALL_ROUND_UP_DATA_FAILURE =
  '    FOOTBALL_ROUND_UP_DATA_FAILURE';

export const SPORT_ROUND_UP_DATA_REQUEST = '    SPORT_ROUND_UP_DATA_REQUEST';
export const SPORT_ROUND_UP_DATA_SUCCESS = '    SPORT_ROUND_UP_DATA_SUCCESS';
export const SPORT_ROUND_UP_DATA_FAILURE = '    SPORT_ROUND_UP_DATA_FAILURE';
