export const F1_TICKER_DATA_REQUEST = '    F1_TICKER_DATA_REQUEST';
export const F1_TICKER_DATA_SUCCESS = '    F1_TICKER_DATA_SUCCESS';
export const F1_TICKER_DATA_FAILURE = '    F1_TICKER_DATA_FAILURE';
